# Modifiez ce document pour modifier le site du sommet

# titre du site
title: Sommet TDJ Togo 2015

# description tel qu'il apparaît sur Google
description:
  Terre des jeunes prévoit un sommet international qui rassemblera des jeunes d'à travers le monde qui oeuvrent bénévolement pour l'environnement.

# slogan ligne 1 (taille moyenne)
slogan_ligne_1:
  Sommet international

# slogan ligne 2 (gros texte)
slogan_ligne_2:
  Terre des jeunes

# slogan ligne 3 en plus petit
slogan_ligne_3:
  Terre des jeunes prévoit un sommet international qui rassemblera des jeunes d'à travers le monde qui oeuvrent bénévolement pour l'environnement.

# entrée de menu de la première section (garder ça court)
menu_section_1:
  S1

# titre de la première section
titre_section_1:
  Tire de la première section

# description de la première section
desc_section_1:
  Ceci est la description de la première section

# grosse image en haut de la page
grosse_image:
  http://terredesjeunes.org/sites/terredesjeunes.org/files/js.JPG

# latitude et longitude du site
emplacement_ll:
  6.428705,1.2117147

# # # # # # # # # # # # # #
#
# SECTION "ACTIONS"
#
# # # # # # # # # # # # # #

actions_titre:
  Actions

actions_desc:
  Quelques-unes des actions entreprises bénévolement par les antennes de Terre des jeunes à travers le monde.


# SVP ne modifiez pas ce qui se trouve sous cette ligne
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
